name: push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.1.15

    - name: Install deps
      run: poetry install
      
    - name: Run Tests and Generate Coverage
      run: tox
